import type { Metadata } from "next";
import { HeroUIProvider } from "@heroui/react";

import "../globals.css";
import Navbar from "../components/navbar";

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <HeroUIProvider className="w-full">
            <Navbar />
            <main className="w-full pt-6 md:max-w-[80%] max-w-[96%] mx-auto">
                {children}
            </main>
        </HeroUIProvider>
    );
}
